### add a new catalog
POST http://localhost:8080/api/catalogs
Content-Type: application/json

{
  "name": "Computer Electronics",
  "description": "a catalog which holds computer electronics",
  "slug": "computer_electronic"
}

### update an existing catalog
PUT http://localhost:8080/api/catalogs
Content-Type: application/json

{
  "id": "f1bd6f58-bb37-4552-a539-fe3fe15ece06",
  "name": "Grocery Itemsxxxx",
  "description": "a catalog which holds grocery itemsxxxxxx",
  "slug": "grocery_itemsxxxxx"
}

### update an existing catalog
PATCH http://localhost:8080/api/catalogs
Content-Type: application/json

{
  "id": "f1bd6f58-bb37-4552-a539-fe3fe15ece06",
  "name": "ماگ جدید 6"
}

### delete a catalog by id
DELETE http://localhost:8080/api/catalogs/c0c7caa6-cc95-4a65-9688-05706b11b986
Content-Type: application/json

### get a catalog with by id
GET http://localhost:8080/api/catalogs/f1bd6f58-bb37-4552-a539-fe3fe15ece06
Content-Type: application/json

### get a catalog by name
GET http://localhost:8080/api/catalogs?name=Computer%20Electronics
Content-Type: application/json

### get a catalog with slug
GET http://localhost:8080/api/catalogs?slug=computer_electronic
Content-Type: application/json

### get all catalogs
GET http://localhost:8080/api/catalogs
Content-Type: application/json

### get all catalogs ordered
GET http://localhost:8080/api/catalogs/ordered
Content-Type: application/json

### get a catalog with its root categories by id
GET http://localhost:8080/api/catalogs/59501b01-64c4-4f4b-a817-9b4915c22715/with-root-categories
Content-Type: application/json
