### add a root category to a catalog
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "laptop",
  "description": "a category that holds laptop computers and belongs to electronics catalog",
  "slug": "laptop_computer",
  "catalogId": {{catalogId_computer_electronics}}
}

### add a descendant category to a root category
POST http://localhost:8080/api/categories/descendants
Content-Type: application/json

{
  "name": "x",
  "description": "x",
  "slug": "x",
  "categoryId" : "79e784ec-b22d-456c-807f-300a21bffc2f",
  "catalogId": "59501b01-64c4-4f4b-a817-9b4915c22715"
}

### update a category
PUT http://localhost:8080/api/categories
Content-Type: application/json

{
  "id": "35980f98-5355-43c9-973e-3d4e59e4acf2",
  "name": "Vegetable Items",
  "description": "a category that holds desktop computers and belongs to Grocery catalog",
  "slug": "vegetable_items",
  "catalogId": "59501b01-64c4-4f4b-a817-9b4915c22715"
}

### remove a category with no descendants
DELETE http://localhost:8080/api/categories/5a84aa6f-fdb4-4dbd-ae11-c67adfcf0c90
Content-Type: application/json

### get a category by its id
GET http://localhost:8080/api/categories/3d009975-4a7d-4b99-ac2a-ba6b653a6d6a
Content-Type: application/json

### get a category by its name
GET http://localhost:8080/api/categories?name=ram
Content-Type: application/json

### get a category by its slug
GET http://localhost:8080/api/categories?slug=ram
Content-Type: application/json

### get a parent category with its level 1 descendants by id
GET http://localhost:8080/api/categories/79e784ec-b22d-456c-807f-300a21bffc2f/with-sub-categories
Content-Type: application/json





### activate a category
PUT http://localhost:8080/api/categories/3ec82e85-da8c-4126-be36-aa4b1b157258/activate
Content-Type: application/json

### deactivate a category
PUT http://localhost:8080/api/categories/3ec82e85-da8c-4126-be36-aa4b1b157258/deactivate
Content-Type: application/json

### get all ancestors categories
GET http://localhost:8080/api/categories/ancestors/78710ae4-cb8d-4756-a403-faa7794ce511
Content-Type: application/json

### get all descendants categories
GET http://localhost:8080/api/categories/descendants/79e784ec-b22d-456c-807f-300a21bffc2f
Content-Type: application/json

### activate or deactivate without versioning (ACTIVE || INACTIVE)
PUT http://localhost:8080/api/categories/3ec82e85-da8c-4126-be36-aa4b1b157258
Content-Type: application/json

{
  "categoryStatus" : "ACTIVE"
}

### activate or deactivate with versioning (ACTIVE || INACTIVE)
PUT http://localhost:8080/api/categories/3ec82e85-da8c-4126-be36-aa4b1b157258/versioned
Content-Type: application/json

{
  "categoryStatus" : "INACTIVE"
}

### find all root categories
GET http://localhost:8080/api/categories/root
Content-Type: application/json


